name: u_do_note
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cloud_firestore: ^4.15.4
  dart_openai: ^5.0.0
  dartz: ^0.10.1
  email_validator: ^2.1.17
  envied: ^0.5.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  introduction_screen: ^3.1.12
  logger: ^2.0.2+1
  riverpod_annotation: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  auto_route_generator: ^7.3.2
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
