name: u_do_note
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cloud_firestore: ^4.15.4
  dart_openai: ^5.0.0
  dartz: ^0.10.1
  email_validator: ^2.1.17
  envied: ^0.5.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  flutter_easyloading: ^3.0.5
  flutter_quill: ^9.3.1
  flutter_riverpod: ^2.4.10
  flutter_speed_dial: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  introduction_screen: ^3.1.6
  logger: ^2.0.2+1
  multi_select_flutter: ^4.1.3
  riverpod_annotation: ^2.3.4
  swipable_stack: ^2.0.0
  flutter_svg: 2.0.10+1
  tutorial_coach_mark: ^1.2.11
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  auto_route_generator: ^7.3.2
  envied_generator: ^0.5.3

flutter:
  assets:
    - lib/assets/
    - assets/
    - lib/assets/fonts/
    - lib/assets/images/
    - lib/assets/images/onboard/
  uses-material-design: true

fonts:
- family: Inter-Bold
  fonts:
    - asset: lib\assets\fonts\Inter-Bold.ttf
- family: Inter-Medium
  fonts:
    - asset: lib\assets\fonts\Inter-Medium.ttf

