name: u_do_note
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cloud_firestore: ^4.15.4
  dart_openai: ^5.0.0
  dartz: ^0.10.1
  email_validator: ^2.1.17
  envied: ^0.5.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_storage: ^11.6.10
  fleather: ^1.17.0
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.12
  flutter_chat_types: ^3.6.2
  flutter_easyloading: ^3.0.5
  flutter_riverpod: ^2.4.10
  flutter_speed_dial: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: 0.19.0
  introduction_screen: ^3.1.6
  logger: ^2.0.2+1
  riverpod_annotation: ^2.3.4
  swipable_stack: ^2.0.0
  flutter_svg: 2.0.10+1
  tutorial_coach_mark: ^1.2.11
  flutter_onboarding_slider: ^1.0.11
  google_mlkit_text_recognition: ^0.11.0
  speech_to_text: ^6.6.0
  shared_preferences: ^2.2.3
  file_picker: ^8.0.1
  syncfusion_flutter_pdf: ^25.1.40
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^25.2.3+1
  responsive_sizer: ^3.3.1
  skeletonizer: ^1.1.2+1
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  page_transition: ^2.1.0
  google_sign_in: ^6.2.1
  easy_localization: ^3.0.7
  parchment_delta: ^1.0.0
  multi_dropdown: ^3.0.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  auto_route_generator: ^7.3.2
  envied_generator: ^0.5.3

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/onboard/
    - assets/images/logo/
    - assets/translations/
  uses-material-design: true

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 600
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 700
    - family: Readex
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 700

