// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDaQbx2XPXwOo-XHVLr_CA8PPSztxUJE',
    appId: '1:504837693421:web:d4314766e46b99a98391e4',
    messagingSenderId: '504837693421',
    projectId: 'u-do-note-0',
    authDomain: 'u-do-note-0.firebaseapp.com',
    storageBucket: 'u-do-note-0.appspot.com',
    measurementId: 'G-NB42WSNQLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkVzqgGRFouB2-h5VMjnbWM939GNIKqw8',
    appId: '1:504837693421:android:0c75e8cce823e09a8391e4',
    messagingSenderId: '504837693421',
    projectId: 'u-do-note-0',
    storageBucket: 'u-do-note-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABPxnoW_EKl6hDV74PrAUEinoq3a0RRME',
    appId: '1:504837693421:ios:9ad4e0a0cb5e014d8391e4',
    messagingSenderId: '504837693421',
    projectId: 'u-do-note-0',
    storageBucket: 'u-do-note-0.appspot.com',
    androidClientId: '504837693421-qrdcclk083gt9bs4di24nhpfo824ae8n.apps.googleusercontent.com',
    iosClientId: '504837693421-5s2665iv83kjir2gbac4hkilrs0nl290.apps.googleusercontent.com',
    iosBundleId: 'com.example.uDoNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABPxnoW_EKl6hDV74PrAUEinoq3a0RRME',
    appId: '1:504837693421:ios:9ad4e0a0cb5e014d8391e4',
    messagingSenderId: '504837693421',
    projectId: 'u-do-note-0',
    storageBucket: 'u-do-note-0.appspot.com',
    androidClientId: '504837693421-qrdcclk083gt9bs4di24nhpfo824ae8n.apps.googleusercontent.com',
    iosClientId: '504837693421-5s2665iv83kjir2gbac4hkilrs0nl290.apps.googleusercontent.com',
    iosBundleId: 'com.example.uDoNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZuWWeYtks_4giT7YXSGkCtPOJ1KVomwE',
    appId: '1:504837693421:web:3b2450420e4d2f928391e4',
    messagingSenderId: '504837693421',
    projectId: 'u-do-note-0',
    authDomain: 'u-do-note-0.firebaseapp.com',
    storageBucket: 'u-do-note-0.appspot.com',
    measurementId: 'G-KFXJ1JG4CM',
  );

}