name: release
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: semver
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Update Pubspec Version
        uses: ibragimovdp/tag-to-version@v1.0.0